### ISSUE TITLE
Изменить тип полей билета и фамилии

### ISSUE THREAD

**Issue by Annndruha** [profcomff/print-webapp#8]
Можно улучшить пользовательский опыт, если номер билета и фамилию сделать как пару логин/пароль. В этом случае браузер будет их автоматически подставлять при повторном использовании.

**Comment by dyakovri** [comment]
У меня браузер и так запоминает поля и синхронизирует
+ поля сохраняют свои значения при перезагрузках страницы
Да и план перейти на печать по логину-паролю рано или позлно
